# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Junwon Kim
description: >- # this means to ignore newlines until "baseurl:"
  Student at @HarbinWanbangSchool.
baseurl: "/" # the subpath of the site
url: "https://junwonkim.netlify.app" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: junwonkim04@outlook.com
      link: mailto:junwonkim04@outlook.com
    - name: Email
      value: junwonkim59@gmail.com
      link: mailto:junwonkim59@gmail.com

  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/junwon-kim-954a662ab/
    - name: GitHub
      link: http://github.com/notj-code
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
